- cloudevents-server/README.md
- cloudevents-server/configs/example-config-sqlite3.yaml
- cloudevents-server/deployments/k8s-dev.yaml
- cloudevents-server/pkg/events/custom/testcaserun/testcaserun.go
- cloudevents-server/skaffold.yaml
> feat(cloudevents-server): add skaffold flow file

- .github/workflows/charts-release.yaml
- charts/cloudevents-server/.helmignore
- charts/cloudevents-server/Chart.yaml
- charts/cloudevents-server/templates/NOTES.txt
- charts/cloudevents-server/templates/_helpers.tpl
- charts/cloudevents-server/templates/deployment.yaml
- charts/cloudevents-server/templates/hpa.yaml
- charts/cloudevents-server/templates/ingress.yaml
- charts/cloudevents-server/templates/service.yaml
- charts/cloudevents-server/templates/serviceaccount.yaml
- charts/cloudevents-server/templates/tests/test-connection.yaml
- charts/cloudevents-server/values.yaml
- cloudevents-server/client/main.go
- cloudevents-server/deployments/k8s-dev.yaml
- cloudevents-server/main.go
- cloudevents-server/skaffold.yaml
- cloudevents-server/test/testcaserun-events.http
> feat(cloudevents-server): add helm chart

- cloudevents-server/client/main.go
- cloudevents-server/ent/client.go
- cloudevents-server/ent/migrate/schema.go
- cloudevents-server/ent/mutation.go
- cloudevents-server/ent/problemcaserun.go
- cloudevents-server/ent/problemcaserun/problemcaserun.go
- cloudevents-server/ent/problemcaserun/where.go
- cloudevents-server/ent/problemcaserun_create.go
- cloudevents-server/ent/problemcaserun_update.go
- cloudevents-server/ent/runtime.go
- cloudevents-server/ent/runtime/runtime.go
- cloudevents-server/ent/schema/problemcaserun.go
- cloudevents-server/pkg/events/custom/testcaserun/testcaserun.go
- cloudevents-server/pkg/events/custom/testcaserun/types.go
Add `reason` filed in table, and adjust the event handler for new problem case reporting palyload structure.
> refactor(cloudevents-server): add `reason` filed

- cloudevents-server/pkg/events/custom/tekton/handler.go
> opt(cloudevents-server): skip notify for task runs

- cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
> reafactor(cloud-events): just deal tekton pipelinerun final state events

- charts/dl/.helmignore
- charts/dl/Chart.yaml
- charts/dl/templates/NOTES.txt
- charts/dl/templates/_helpers.tpl
- charts/dl/templates/deployment.yaml
- charts/dl/templates/hpa.yaml
- charts/dl/templates/ingress.yaml
- charts/dl/templates/service.yaml
- charts/dl/templates/serviceaccount.yaml
- charts/dl/templates/tests/test-connection.yaml
- charts/dl/values.yaml
> feat(charts): add chart for `dl` server

- .github/workflows/charts-release.yaml
> ci: fix chart release flow

- cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
- cloudevents-server/pkg/events/custom/tekton/handler_taskrun.go
> fix(cloudevents): fix notify conditions

- cloudevents-server/pkg/config/config.go
- cloudevents-server/pkg/events/custom/tekton/handler.go
- cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
- cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun_test.go
- cloudevents-server/pkg/events/custom/tekton/handler_taskrun.go
- cloudevents-server/pkg/events/custom/tekton/handler_taskrun_test.go
- cloudevents-server/pkg/events/custom/tekton/handler_test.go
- cloudevents-server/pkg/events/custom/tekton/lark.go
> fix(cloudevents): fix UT cases

- cloudevents-server/pkg/events/custom/tekton/lark.go
- cloudevents-server/pkg/events/custom/tekton/lark_templates/pipelinerun-notify.yaml.tmpl
> opt(cloudevents-server): opt notify card UI

- cloudevents-server/pkg/events/custom/tekton/lark.go
- cloudevents-server/pkg/events/custom/tekton/lark_templates/tekton-run-notify.yaml.tmpl
- cloudevents-server/pkg/events/custom/tekton/types.go
> fix(cloudevents-server): refactor results parts for tekton run notification message

- tibuild/api/api.go
- tibuild/pkg/rest/controller/dev_build_handler.go
- tibuild/pkg/rest/service/dev_build_service.go
- tibuild/pkg/rest/service/gh_client.go
- tibuild/pkg/rest/service/gh_client_test.go
- tibuild/pkg/webhook/service/tekton_event.json
- tibuild/tbctl/tbctl.py
- GitHub API rate limit exceeded, need login to github in order to increase limit
- add token to github client
- some refract for tbctl.py
> fix: github require loggin to avoid rate limit

- tibuild/pkg/rest/service/dev_build_service.go
- tibuild/pkg/webhook/handler/cloudevent_handler.go
- tibuild/pkg/webhook/service/cloudevent.go
Why:
- fix some bug on parsing event
- log enough information
> fix: tekton null status

- cloudevents-server/configs/example-config-sqlite3.yaml
- cloudevents-server/configs/example-config.yaml
- cloudevents-server/handlers.go
- cloudevents-server/pkg/config/config.go
- cloudevents-server/pkg/events/custom/tekton/handler.go
- cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
- cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun_test.go
- cloudevents-server/pkg/events/custom/tekton/handler_taskrun.go
- cloudevents-server/pkg/events/custom/tekton/handler_taskrun_test.go
- cloudevents-server/pkg/events/custom/tekton/lark.go
- cloudevents-server/pkg/lark/client.go
> feat(cloudevents-server): support set receivers by event types

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
> ci: full clone and fetch tags for skaffold build

- change-insight/OWNERS
- cloudevents-server/OWNERS
- tibuild/OWNERS
> chore: add labels in `OWNERS` files

- tibuild/pkg/webhook/service/cloudevent.go
Why:
- avoid nil pointer access
> fix: StartTime maybe nil

- tibuild/pkg/webhook/service/cloudevent.go
Why:
- need event body for better debug
> chore: change event log to info

- tibuild/docs/docs.go
- tibuild/docs/swagger.json
- tibuild/docs/swagger.yaml
- tibuild/pkg/rest/service/dev_build_service.go
- tibuild/pkg/rest/service/model.go
- change pipeline url to pipeline urls because tekton has multiple pipeline
> feat: update pipeline url from single to list

- cloudevents-server/configs/example-config-sqlite3.yaml
- cloudevents-server/configs/example-config.yaml
- cloudevents-server/pkg/config/config.go
- cloudevents-server/pkg/events/custom/tekton/handler.go
- cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
- cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun_test.go
- cloudevents-server/pkg/events/custom/tekton/handler_taskrun.go
- cloudevents-server/pkg/events/custom/tekton/handler_taskrun_test.go
- cloudevents-server/pkg/events/custom/tekton/testdata/event-taskrun.failed-standalone.json
> feat(cloudevents-server): support notify by event subject

- cloudevents-server/pkg/events/custom/tekton/handler.go
- cloudevents-server/pkg/events/handler/handler.go
> chore(cloudevents-server): add debug log for tailing container log

- publisher/pkg/impl/tiup/funcs.go
- publisher/pkg/impl/tiup/publisher.go
- publisher/pkg/impl/tiup/types.go
> feat(publisher): add rate limit for tiup nightly publishing

- tibuild/pkg/rest/service/cloud_event_client.go
- tibuild/pkg/rest/service/dev_build_service.go
- support `-builderImg` cli option for tekton engine.
- support tag ref type for tekton engine.
> feat(tibuild): support dev-build with image builder param for tekton engine

- cloudevents-server/pkg/events/tekton/handler.go
- cloudevents-server/pkg/events/tekton/lark_templates/tekton-run-notify.yaml.tmpl
- cloudevents-server/pkg/events/tekton/types.go
> feat(cloudevents-server): add failed message to lark notification

- publisher/example/config/worker-example.yaml
- publisher/pkg/impl/tiup_worker.go
> fix(publisher): fix failure notify message

- chatops-lark/pkg/events/handler/cherrypick.go
- chatops-lark/pkg/events/handler/devbuild.go
- chatops-lark/pkg/events/handler/root.go
* Provide a more friendly prompt when the user's trigger command is incorrect or missing parameters.
* Some necessary debugging information has been added to the handler module.
> feat(chatops-lark): Enhance the user-friendliness of cmd prompts.

- chatops-lark/pkg/events/handler/devbuild.go
> chore(chatops-lark): update devbuild examples and clarify gitRef option format

- insight/transform/github-ticket-json-to-db.ts
- Fix filename typo from `tickit` to `ticket`
- Add new fields: body, timeline, cross_references, branches 
- Improve error handling and progress output 
- Fix table creation SQL and insert logic
> refactor(insight/transform): rename and update GitHub ticket import script

- tibuild/pkg/webhook/service/cloudevent.go
- Rename parse_tekton_image to parseTektonImage for Go naming consistency
- Extend TektonImageStruct to include repo, platform, tag, tags, and multi_arch_tags
- Construct image URLs using repo and tag fields
- Add support for multi-arch images by appending entries with multi-arch tags
> feat(tibuild): refactor Tekton image parsing and support multi-arch tags
