PingCAP-QE/ee-apps

- tibuild/api/api.go
- tibuild/commons/configs/config.go
- tibuild/commons/configs/config_test.go
- tibuild/configs/config_example.yaml
- tibuild/docs/docs.go
- tibuild/docs/swagger.json
- tibuild/docs/swagger.yaml
- tibuild/pkg/rest/controller/common.go
- tibuild/pkg/rest/controller/dev_build_handler.go
- tibuild/pkg/rest/repo/dev_build_repo_test.go
- tibuild/pkg/rest/service/dev_build_service.go
- tibuild/pkg/rest/service/dev_build_service_test.go
- tibuild/pkg/rest/service/error.go
- tibuild/pkg/rest/service/model.go
- tibuild/tbctl/tbctl.py
Why:
- some users want use devbuild for nighly, hoping to push to given target image address
How:
- add basic auth, with shared token
- allow given target image if he is admin
- add a big account for front end and chat-bot
- allow GitRef like: branch/feature/...
> feat: add basic auth to allow target

- dl/ks3.go
- dl/pkg/ks3/cfg.go
> fix(dl): fix yaml config and get object logic

- cloudevents-server/configs/example-config-sqlite3.yaml
- cloudevents-server/ent/client.go
- cloudevents-server/ent/problemcaserun_update.go
- cloudevents-server/ent/runtime/runtime.go
- cloudevents-server/pkg/events/custom/testcaserun/handler.go
- cloudevents-server/pkg/events/custom/testcaserun/types.go
error: missing required field "ProblemCaseRun.reason"
> fix(cloudevents): fix error for case run report

- tibuild/pkg/rest/service/model.go
- some image length can longer than 64 char
> fix: some builder image may longer than 64 char

- tibuild/docs/docs.go
- tibuild/docs/swagger.json
- tibuild/docs/swagger.yaml
- tibuild/pkg/rest/repo/dev_build_repo_test.go
- tibuild/pkg/rest/service/dev_build_service.go
- tibuild/pkg/rest/service/dev_build_service_test.go
- tibuild/pkg/rest/service/model.go
- no need to  use multiple status, because now we only use one pipeline engine
> refract: simplify tekton status

- tibuild/docs/docs.go
- tibuild/docs/swagger.json
- tibuild/docs/swagger.yaml
- tibuild/pkg/rest/service/dev_build_service.go
- tibuild/pkg/rest/service/dev_build_service_test.go
- tibuild/pkg/rest/service/model.go
- tibuild/pkg/webhook/service/cloudevent.go
Why:
- rename orasfile to oci file
> refract: rename orasfile to oci file

- tibuild/pkg/rest/service/dev_build_service.go
- tibuild/pkg/rest/service/dev_build_service_test.go
- tibuild/pkg/rest/service/model.go
- fix relation between sha256 and origin file
> fix: sha256sum for oci artifact

- tibuild/docs/docs.go
- tibuild/docs/swagger.json
- tibuild/docs/swagger.yaml
- tibuild/pkg/rest/service/dev_build_service.go
- tibuild/pkg/rest/service/dev_build_service_test.go
- tibuild/pkg/rest/service/model.go
- tibuild/pkg/webhook/service/cloudevent.go
Why:
- currently the pipeline start at and end at are not properly set
> fix: add `startAt` and `endAt` for Tekton runs

- cloudevents-server/pkg/events/custom/tekton/handler.go
> feat(cloudevents): fix not add the not runned steps in notificatioins

- cloudevents-server/pkg/config/config.go
- cloudevents-server/pkg/events/custom/tekton/handler.go
- cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
- cloudevents-server/pkg/events/custom/tekton/handler_taskrun.go
- cloudevents-server/pkg/events/custom/tekton/lark.go
- cloudevents-server/pkg/events/custom/tekton/lark_templates/tekton-run-notify.yaml.tmpl
- cloudevents-server/pkg/events/custom/tekton/types.go
> feat(cloudevents-server): append tail logs for failed steps

- cloudevents-server/pkg/events/custom/tekton/handler.go
> fix(cloudevents/server): fix ssl verify error for internal server url

- cloudevents-server/pkg/events/custom/tibuild/handler.go
> refactor(cloudevents-server): add debug log to diagnose the devbuild issue

- tibuild/pkg/rest/service/cloud_event_client.go
- tibuild/pkg/rest/service/cloud_event_client_test.go
- tibuild/pkg/rest/service/dev_build_service.go
- tibuild/pkg/rest/service/gh_client.go
- tibuild/pkg/rest/service/gh_client_test.go
- tibuild/pkg/rest/service/interface.go
- tibuild/pkg/rest/service/model.go
> feat(tibuild): support build with tekton engine for pull requests

- tibuild/README.md
- tibuild/website/src/layout/Header.js
> fix(tibuild): update user guide link

- dl/cmd/server/main.go
- dl/ks3.go
- dl/oci.go
- dl/pkg/oci/cfg.go
- dl/pkg/oci/download.go
> feat(dl): add credential support for dl service

- tibuild/pkg/rest/service/artifact_helper.go
> fix(tibuild): fix image sycn source validation regexp

- charts/tiup-publisher/Chart.yaml
- charts/tiup-publisher/templates/deployment.yaml
This pull request includes updates to the `charts/tiup-publisher` to reflect new versions and simplify the deployment configuration. The most important changes include updating the chart and application versions, and removing unnecessary liveness and readiness probes.
Version updates:
* [`charts/tiup-publisher/Chart.yaml`](diffhunk://#diff-f43428ddb40c8df41fbc79c59e4539afcd52bbe410ff3c968d38619b7eca29f5L18-R24): Updated the chart version from `0.1.0` to `0.2.0` and the application version from `v0.1.0` to `v20240228-83-g645b571`.
Deployment configuration simplification:
* [`charts/tiup-publisher/templates/deployment.yaml`](diffhunk://#diff-362d766865ad9f0819673029b8220a55e60773e2ae38099a76680329927dd43dL43-L50): Removed the `livenessProbe` and `readinessProbe` configurations to simplify …
> fix(tiup-publisher): update tiup-publisher chart

- tiup-publisher/handler.go
- tiup-publisher/main.go
> chore(tiup-publisher): add logs

- tiup-publisher/handler.go
- tiup-publisher/handler_test.go
- tiup-publisher/main.go
- tiup-publisher/types.go
> feat(tiup-publisher): add notify when publish failed

- publisher/pkg/tiup/funcs.go
This pull request includes a small but important change to the `splitRepoAndTag` function in the `publisher/pkg/tiup/funcs.go` file. The change corrects the logic for determining the delimiter used to split the repository and tag in a given URL.
* [`publisher/pkg/tiup/funcs.go`](diffhunk://#diff-1d210de00b8fd357f0aee036762196bb4595ea47ab660b1d332bb04baeeb5e97L241-R241): Modified the `splitRepoAndTag` function to correctly identify URLs containing `@sha256:` and use the appropriate delimiter for splitting.
> fix(publisher): fix `splitRepoAndTag` function

- publisher/cmd/worker/main.go
- publisher/pkg/config/config.go
- publisher/pkg/impl/tiup/publisher.go
- publisher/pkg/impl/tiup/service.go
This pull request introduces Redis integration into the `publisher` service, refactoring the code to accommodate the new Redis client and updating the handling of Redis commands. The most important changes include adding the Redis client configuration, modifying the `Publisher` and `Service` structs, and updating Redis command methods.
* [`publisher/cmd/worker/main.go`](diffhunk://#diff-0c11d49a84dbe2803f3a531ba845598d4d2c9f4be0b64f1f2ff347d8e9afcb45R14): Added Redis client configuration and passed the Redis client to the `tiup.NewPublisher` function. [[1]](diffhunk://#diff-0c11d49a84dbe2803f3a531ba845598d4d2c9f4be0b64f1f2ff347d8e9afcb45R14) [[2]](diffhunk://#diff-0c11d49a84dbe2803f3a531ba845598d4d2c9f4be0b64f1f2ff347d8e9afcb45R52-R65)
* …
> fix(publisher): fix redis command usage

- publisher/cmd/worker/init.go
- publisher/cmd/worker/main.go
- publisher/example/config/service-example.yaml
- publisher/example/config/worker-example.fileserver.yaml
- publisher/example/config/worker-example.tiup.yaml
- publisher/pkg/impl/fileserver_worker.go
- publisher/pkg/impl/funcs_fs.go
> feat(publisher): add fileserver worker

- tibuild/pkg/rest/service/cloud_event_client.go
> fix(tibuild): fix devbuild tekton cloudevent extension key

- change-insight/lib/github/common.go
This pull request includes several changes to the `change-insight/lib/github/common.go` file to enhance security and improve error handling. The most important changes include the addition of environment variable support for GitHub tokens and improved error handling for API calls.
Enhancements to security:
* [`change-insight/lib/github/common.go`](diffhunk://#diff-5251738818d44ec5f50892200dc833237918634443d53426422f57f0a4ea14a9L28-R57): Replaced the hardcoded GitHub token with a function that retrieves the token from the environment variable `GITHUB_TOKEN`.
Improvements to error handling:
* [`change-insight/lib/github/common.go`](diffhunk://#diff-5251738818d44ec5f50892200dc833237918634443d53426422f57f0a4ea14a9L28-R57): Added error handling for unexpected status codes in the `apiCall` …
> fix: github token getter

- cloudevents-server/pkg/events/handler/kafka.go
wrong added the defer close call, it will caused the consumer reading failure.
I tested the change manually, it's passed.
> fix(cloudevents-server): fix the issue of the EventConsumer close calls

- publisher/pkg/impl/tiup_worker.go
> feat(publisher): add retry for tiup publishing

- publisher/Dockerfile
- publisher/go.mod
- publisher/pkg/impl/funcs_fs.go
- publisher/pkg/impl/funcs_fs_test.go
- publisher/pkg/impl/tiup_worker.go
- publisher/pkg/impl/tiup_worker_test.go
avoid conflict with the branch objects
> feat(publisher): add tag artifacts to fileserver

- publisher/pkg/impl/funcs_fs.go
- publisher/pkg/impl/funcs_fs_test.go
- from `centos7/*.tar.gz` to `<os>_<arch>/*.tar.gz`
> refactor(publisher): update the target bucket key for publishing to fileserver

- publisher/pkg/impl/funcs_tiup.go
> feat(publisher): support profile for tiup publications

- publisher/pkg/impl/funcs_tiup.go
- publisher/pkg/impl/funcs_tiup_test.go
> fix(publisher): fix ga oci judgement

- tibuild/go.mod
- tibuild/pkg/rest/service/dev_build_service.go
- tibuild/pkg/rest/service/gh_client.go
- tibuild/pkg/rest/service/gh_client_test.go
- tibuild/pkg/rest/service/interface.go
Usage:
/devbuild trigger --engine tekton -e enterprise tidb v8.5.0-dev commit/<sha>
> feat(tibuild): support commit to build

- tibuild/pkg/rest/service/cloud_event_client.go
This pull request includes a small change to the `tibuild/pkg/rest/service/cloud_event_client.go` file. The change adds a new extension parameter to the cloud event for the `paramProfile` field.
* [`tibuild/pkg/rest/service/cloud_event_client.go`](diffhunk://#diff-12f7cc6dce0ce0b270c4b652690b1d70621d252829df2db7ec36fa48691714b6R81): Added `paramProfile` extension to the cloud event in the `newDevBuildCloudEvent` function.
> feat(tibuild): support profile for tekton engine

- chatops-lark/go.mod
- chatops-lark/go.sum
- chatops-lark/pkg/events/handler/cherrypick.go
- chatops-lark/pkg/events/handler/root.go
This pull request includes several changes to enhance the `chatops-lark` package, focusing on improving error handling, adding caching, and extending functionality. The most important changes include adding a new dependency, enhancing the `rootHandler` struct, and improving the `cherryPickInvite` function.
* Added `github.com/allegro/bigcache/v3 v3.1.0` to the `go.mod` file.
* Added `github.com/rs/zerolog/log` for logging in `cherrypick.go` and `root.go`. [[1]](diffhunk://#diff-f58f7cb1bbf4c74d32dee9cd3f59873035c52a0fd3c0ed8e23325eba6d4561b0R13) [[2]](diffhunk://#diff-0a367f483d9dcab41f47dd231972be9d8e05084330e66c00b27a7bbee7fd196aR9-R13)
* Enhanced error logging in the `cherryPickInvite` function to include the status code when an invitation fails.
* Introduced `bigcache` to cache event …
> feat(chatops-lark): avoid handling for dup events

- tibuild/Dockerfile
- tibuild/pkg/rest/service/artifact_helper.go
This pull request includes a modification to the regular expression used to match source image URLs in the `artifact_helper.go` file. The change expands the scope of acceptable URLs to include additional domains.
Changes to regular expression:
* [`tibuild/pkg/rest/service/artifact_helper.go`](diffhunk://#diff-8952fb6234b7e7797b74c5ddf576757ece54b503266c7c71a80fb4b726431b24L48-R48): Updated the `source_image_reg` regular expression to match URLs from `qa`, `pingcap`, and `tikv` domains.
> fix(tibuild): fix src image checking regexp

- chatops-lark/README.md
- chatops-lark/cmd/server/main.go
This pull request introduces significant updates to the `chatops-lark` bot, including new documentation, the addition of a health check server, and improvements to the main server functionality. The most important changes are summarized below:
* [`chatops-lark/README.md`](diffhunk://#diff-d7ff5847475dddd947f9882814d5016b004e1281ddeb633fc70c37217d5a5d88R1-R20): Added a new section detailing how to debug, run locally, and deploy the `chatops-lark` bot. This includes configuration examples and deployment instructions using FluxCD.
* [`chatops-lark/cmd/server/main.go`](diffhunk://#diff-59a24a1fb5af6bcb691d8411a211b0df320f16edceee725cc1076db374c51a0aR25-R47): Introduced a health check HTTP server that listens on a configurable address (`http-addr`) and responds with "OK" on the `/healthz` …
> feat(chatops-lark): add health checking

- .github/workflows/charts-release.yaml
- charts/chatops-lark/.helmignore
- charts/chatops-lark/Chart.yaml
- charts/chatops-lark/templates/NOTES.txt
- charts/chatops-lark/templates/_helpers.tpl
- charts/chatops-lark/templates/deployment.yaml
- charts/chatops-lark/templates/hpa.yaml
- charts/chatops-lark/templates/service.yaml
- charts/chatops-lark/templates/serviceaccount.yaml
- charts/chatops-lark/templates/tests/test-connection.yaml
- charts/chatops-lark/values.yaml
This pull request introduces a new Helm chart for the `chatops-lark` application, along with necessary configurations and templates. The changes include the addition of new files and modifications to existing ones to support the deployment and management of the `chatops-lark` application using Helm.
* **Chart Configuration:**
* [`charts/chatops-lark/Chart.yaml`](diffhunk://#diff-e6df411db3462581ecff43a0fa950e5dbbefb5d40548ccdca1b53db00dc415cbR1-R24): Defines the metadata for the `chatops-lark` Helm chart, including its version, description, and type.
* [`charts/chatops-lark/values.yaml`](diffhunk://#diff-2de6c72e0ad7f9dba9f12d675140522cd65cda9ba22f75e2d62090a2cea95e95R1-R115): Provides default values for the `chatops-lark` chart, including image repository, service account settings, pod …
> feat(charts): add helm chart for chatops-lark app

- charts/chatops-lark/Chart.yaml
- charts/chatops-lark/templates/NOTES.txt
- charts/chatops-lark/templates/deployment.yaml
This pull request includes changes to the Helm chart for the `chatops-lark` application to update the version, simplify the NOTES.txt template, and fix the volume mounts and volumes configuration in the deployment template.
Version update:
* [`charts/chatops-lark/Chart.yaml`](diffhunk://#diff-e6df411db3462581ecff43a0fa950e5dbbefb5d40548ccdca1b53db00dc415cbL18-R18): Incremented the chart version from 0.1.0 to 0.1.1.
Template simplification:
* [`charts/chatops-lark/templates/NOTES.txt`](diffhunk://#diff-c6cbde6d041d805f29e61d924013c3ebfd7ae81d7adf747b6760aab0bedf3b35L2-R3): Removed the conditional block for ingress and simplified the command to get the application URL when service type is `NodePort`.
Configuration fixes:
* [`charts/chatops-lark/templates/deployment.yaml`](diffhunk://#diff-21 …
> fix(charts): fix chatops-lark deployment manifest templates

- chatops-lark/pkg/events/handler/root.go
- chatops-lark/pkg/response/command-response.yaml.tmpl
Also add more level for responses:
- skip: color gray.
- info: color blue.
Added two type error types. Here's how you can use these error types in the context of the provided code:
1. **Define Errors**: You can define errors as `InformationError` or `SkipError` to represent different levels of errors.
```go
var infoErr InformationError = errors.New("this is an informational message")
var skipErr SkipError = errors.New("this operation was skipped")
```
2. **Handle Errors**: When handling commands, you can return these errors to indicate specific conditions.
```go
func handleCommand(ctx context.Context, command string) (string, error) {
// Your command handling logic
// Return an informational error
if someCondition {
return "Some message", infoErr
}
// Return a skip error
if …
```
> fix(chatops-lark): remove the dup response

- chatops-lark/.gitignore
- chatops-lark/README.md
- chatops-lark/pkg/events/handler/root.go
The current bot will listen to and reply to all group messages. To avoid disrupting other conversations in the group, it needs to only respond to messages that mention @bot.
> feat(chatops-lark): support reply to group mention bot message

- chatops-lark/README.md
- chatops-lark/cmd/server/main.go
- chatops-lark/pkg/botinfo/client.go
- chatops-lark/pkg/botinfo/client_test.go
- chatops-lark/pkg/events/handler/root.go
Get botname directly from the API.
> feat(chatops-lark): get bot name from api 

- insight/README.md
- insight/crawlers/ci/prow-jobs.test.ts
- insight/crawlers/ci/prow-jobs.ts
Deno is suitable to implement crawler, comparing with python, we do not need any other dependencies to install before run it.
You can just it with one command:
```bash
deno run <the-script>.ts
```
> feat(insight): add ci job crawler

- chatops-lark/go.mod
- chatops-lark/go.sum
- chatops-lark/pkg/events/handler/devbuild.go
- chatops-lark/pkg/events/handler/devbuild_trigger.go
- tibuild/pkg/rest/service/cloud_event_client.go
… for devbuild
Added platform option to specify build platform in devbuild trigger.
> feat(chatops-lark): update tibuild dependency and add platform option for devbuild

- chatops-lark/README.md
- chatops-lark/config.yaml.example
- chatops-lark/pkg/events/handler/root.go
- Move app credentials to config file and make CLI options optional.
- Replace global commandConfigs variable with rootHandler.commandRegistry field.
> fix(chatops-lark): update credential configuration and command registry

- chatops-lark/pkg/botinfo/client.go
- chatops-lark/pkg/botinfo/client_test.go
- chatops-lark/pkg/events/handler/func_lark.go
- chatops-lark/pkg/events/handler/root.go
- chatops-lark/pkg/response/reply.go
* Only reply in group chat conversations by creating a topic, and reply directly in one-on-one chats.
* In a private one-on-one chat, remind the user that they do not need to @ bot.
> feat(chatops-lark): lark bot reply enhance

- tibuild/pkg/rest/service/dev_build_service_test.go
- tibuild/pkg/rest/service/model.go
This commit renames EditionExperimental const to EditionExperiment to match
expected build edition name "experiment" in all references.
> fix(tibuild): fix experimental edition name to experiment

- .github/workflows/weekly-release.yaml
Creates a workflow that runs every Sunday at 00:00 UTC to automatically create a new GitHub release when changes are detected since the previous release.
The workflow can also be triggered manually.
> ci: add weekly automated GitHub release workflow

- cloudevents-server/pkg/events/handler/kafka.go
- cloudevents-server/pkg/kafka/producer.go
kafka write config
- Add timeout controls to Kafka write operations
- Add context timeout, measure duration in handler, and configure writer with explicit timeouts for better error handling.
> fix(cloudevents-server): update

- chatops-lark/pkg/config/config.go
- chatops-lark/pkg/events/handler/func_lark.go
- chatops-lark/pkg/events/handler/root.go
- chatops-lark/pkg/events/handler/types.go
Parse and attach GitHub ID from Lark user custom attributes if configured.
> feat(chatops-lark): add support for GitHub ID custom user attribute
